### ISSUE TITLE
Throw Exception when overriding existing Image metadata?

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#149]
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1496/files#r1838177488

![Image](https://github.com/user-attachments/assets/9b351b74-e83a-4b2a-b1b3-5334e0f606ec)

## Criteria for ready

Is this correct and worth doing?

**Comment by amartya4256** [comment]
I rechecked the method. It doesn't seem to have any consequences since, there is nothing else done in this method other than setting the metadata and it is not called from any place where it is trying to override the existing metadata, however for good practices, I'll add a line to throw exception in such case. Although, even with the current implementation, there is no issue since once a metadata has been set, it can only be changed/cleaned by the resource cleaner and hence, setting a new metadata semantically doesn't make sense and neither it is happening in the current implementation.
