### ISSUE TITLE
Extract image data provider details into internal subclasses

### ISSUE THREAD

**Issue by akoch-yatta** [vi-eclipse/Eclipse-Platform#153]
Extract image creation strategy details into internal suclasses, e.g. ImageDataProvider, ImageFilenameProvider, etc.

**Comment by HeikoKlare** [comment]
Correct me if I am wrong, @akoch-yatta, but wasn't the goal of the Image refactoring to get rid of image-type-specific metadata, in particular the `initialNativeZoom` that is not relevant for images based on data or file name providers? So that a concrete image then either has an initial zoom with the according image data that need to be scaled upon requesting data at a different zoom or has some data provider that is capable of providing the correct data without any data at some initial zoom.

**Comment by akoch-yatta** [comment]
Yes, problem is extracting the "base case" is much more complicated as expected because some of those attributes are used in other parts of SWT directly. Therefor we decided to start with extracting only the "new" cases. But I think we were missing a followup ticket, so I added #171
